export const ActionTypes = {
        SET_CHARACTERS : "SET_CHARACTERS",
        SELECTED_CHARACTER: "SELECTED_CHARACTER",
        REMOVE_SELECTED_CHARACTER: "REMOVE_SELECTED_CHARACTER",
        REMOVE_SELECTED_CHARACTERS: "REMOVE_SELECTED_CHARACTERS",
        ADD_TO_FAVORITE: "ADD_TO_FAVORITE",
        REMOVE_FROM_FAVORITE: "REMOVE_FROM_FAVORITE",
        SET_PLANET : "SET_PLANET",

}